services:
  - docker
before_install:
  - docker build -t tensorflow-gpu-geo .
script:
  - docker run -ti tensorflow-gpu-geo R --version | grep -q "3."
  - docker run -ti tensorflow-gpu-geo R -e 'library(sf)'



